import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import Nav from "../../components/Chat/Shared/Nav";
import ProtectedRoute from "@/components/Auth/ProtectedRoute";
import ProfileDialog from "@/components/Profile/ProfileDialog";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"], // Add weights as needed
  variable: "--font-playfair",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={playfair.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute>
          <div className="flex min-h-screen flex-col lg:flex-row">
            <Nav />
            <div className="flex-1 main-content transition-all lg:ml-[250px] duration-300 relative">
              
              <div className="absolute top-5 right-5 z-50">
                <ProfileDialog />
              </div>
              <div
                className="min-h-[100vh]  "
                style={{
                  background:
                    "radial-gradient(circle at top right, #0129F480 , black 40%)",
                }}
              >
                {children}
              </div>
            </div>
          </div>
        </ProtectedRoute>
      </body>
    </html>
  );
}
